### PR TITLE
Making getInverse aware of null state -

### LINKED ISSUE #616: [place order] wrong validation when set Max bidding price to 0
1. open app
2. open some active public auction
3. fill in the Amount field
4. Fill in the Max bidding price field with 0

**Actual Result:** validation message under the Amount field appears

**Exp.result:**  validation under the Max bidding price field appears: 'Max bidding price must be bigger than <>'

### PR DESCRIPTION
**Pull request by josojo**
closes #616

### CODE REVIEW

File: src/components/auction/Orderbook/index.tsx [hunk 1]
```diff
@@ -59,8 +59,8 @@ export const OrderBook: React.FC<OrderbookProps> = (props) => {
 
   if (showChartsInverted(baseToken)) {
     for (const p of processedOrderbook) {
-      p.priceNumber = getInverse(p.price, NUMBER_OF_DIGITS_FOR_INVERSION)
-      p.priceFormatted = getInverse(p.price, NUMBER_OF_DIGITS_FOR_INVERSION).toString()
+      p.priceNumber = Number(getInverse(p.price.toString(), NUMBER_OF_DIGITS_FOR_INVERSION))
```
Comment (josojo) [inline src/components/auction/Orderbook/index.tsx:62]: This is the only place where a problem would arise, as Number(`-`) = NAN

But since   p.priceNumber = NAN is not causing problems, AFAIK, I would leave it that way. I am not sure how to better deal with it. Not showing the orderbook in such a case is not an option for me.

**Comment by elena-zh** [comment]
Hey @josojo , 

The linked #616 issue  seems to be still reproducible in this pr: 
image

However, another issue,  #646, is not reproducible there. 
Could you please clarify which bug you have fixed there: #646 or  #616?

Thanks

**Comment by josojo** [comment]
>However, another issue, #646, is not reproducible there.
Could you please clarify which bug you have fixed there: #646 or #616?

These issues are very much related. Let me both tackle in this PR

**Comment by josojo** [comment]
closes #646 as well.

**Review by henrypalacios — APPROVED** [review]
Great!

**Comment by elena-zh** [comment]
@josojo , 
I'm still able to reproduce the #616 issue after the latest changes=(
image

Please, open this auction auctionId=138&chainId=4 and follow the next steps:
1. fill in an amount with a valid value
2. fill in the price field with 0
then, you will receive an irrelevant validation message for the Amount field, however, validation message for the price field should be displayed.

**Comment by elena-zh** [comment]
@josojo , now everything LGTM!
Thank you!
